#!/bin/bash
###TO USE THIS SCRIPT, TYPE, FOR EXAMPLE: sh sendjobs PARTICLE ENERGY SEED NEV JOBS
###source /home/rxz/GAMOS4/GAMOS.4.0.0/config/confgamos.sh
source /home/gamos/gamos/GAMOS.6.1.0/config/confgamos.sh

### SET THE VARIABLES TO BE READ FROM THE COMMAND LINE

seed=$1 ## RANDOM SEED NUMBER ex. 1111
nev=$2 ## NUMBER OF EVENTS PER JOB
njobs=$3 ## NUMBER OF JOBS TO RUN
nparallel=$4 ## PARALLEL NUMBER
np=10
### START THE LOOP OF THE NUMBER OF JOBS
nj=0
while 
	test $nj -lt $njobs
	do

nskip=$(($(($nj*$np+$nparallel))*$nev))

		### SET THE SUFFIX OF THE OUTPUT FILES
    	SUFFIX=$nj"th_subjob_"$nparallel"th_parallel"
  		echo " SUFFIX = $SUFFIX "
		### COPY THE INPUT FILE INTO A NEW ONE (SO THAT YOU CAN KEEP TRACK OF THE DIFFERENT FILES THAT ARE RUN)
  		new_inputfile="sd_"$SUFFIX
  		log_inputfile=$new_inputfile".log"
  		echo " The new input file = " $new_inputfile
		### SUBSTITUTE IN THE NEW INPUT FILE THE VARIABLES FROM THE COMMAND LINE
  		awk -v seed=$seed -v nev=$nev -v nj=$nj -v SUFFIX=$SUFFIX -v nskip=$nskip '{
    	if($1=="/run/beamOn") {printf("%s %s \n",$1, nev) }      
    	else if ($1=="/gamos/random/setSeeds") {printf("%s %s %s\n",$1, seed, seed+nj) }
		else if($2=="RTGeneratorPhaseSpace:FileName") {printf("%s %s %s\n",$1,$2,"/media/sf_share_ubuntu_12/TrueBeam_06FFF_phsp/TrueBeam_06FFF_v2") }
		else if($2=="RTGeneratorPhaseSpace:NEventsSkip") {printf("%s %s %s\n",$1,$2,nskip) }
		
		else if($2=="DosePrinter") {printf("%s %s %s\n",$1,"DP_"SUFFIX,$3) }
		else if($2=="LocalCherenkovPrinter") {printf("%s %s %s\n",$1,"LCP_"SUFFIX,$3) }
		else if($2=="GmTrackDataTextFileUA_inclusion_optical_end_filter:FileName") {printf("%s %s %s\n",$1,		$2,"inclusion_data_"SUFFIX) }

		else { print $0 }
  		}' "./sd.in" > $new_inputfile".in"

		## RUN JOB IN FOREGROUND
		gamos $new_inputfile".in" 2>&1 | tee $log_inputfile

		### INCREMENT THE JOB NUMBER BY 1
		nj=$(($nj + 1))
		seed=$(($seed + 1))
done

