#!/bin/bash
###TO USE THIS SCRIPT, TYPE, FOR EXAMPLE: sh starjobs NAME NJOBS HOURS PROCESSORS NODES CELL

### SET THE VARIABLES TO BE READ FROM THE COMMAND LINE

NPARALLEL=$1 ### NUMBER OF PARALLEL JOBS TO EXECUTE
NEV=$2 ## NUMBER OF EVENTS TOTAL
PERJOB=$3 ## EVENTS PER JOB
NJOBS=$(($NEV/$PERJOB/$NPARALLEL))
	
# CREATE THE PARALLEL SCRIPT
rm -f script.sh
echo "#!/bin/bash" >> script.sh
echo "source source /home/gamos/gamos/GAMOS.6.1.0/config/confgamos.sh" >> script.sh
for ((n = 0; n<NPARALLEL-1; n++))
	do
		echo "sh sendjobs" $(($n+1000)) $PERJOB $NJOBS $n "&" >> script.sh
	done
echo "sh sendjobs" $(($n+1000)) $PERJOB $NJOBS $n >> script.sh

# RUN THE PBS SCRIPT
sh ./script.sh

